### ISSUE TITLE
(IMPORT FAILED) comfyui-art-venture 

### ISSUE THREAD

**Issue by littleyeson** [sipherxyz/comfyui-art-venture#21]
(IMPORT FAILED) [comfyui-art-venture](https://github.com/sipherxyz/comfyui-art-venture)
Nodes: ImagesConcat, LoadImageFromUrl, AV_UploadImage
Conflicted Nodes:
ColorCorrect [ComfyUI-post-processing-nodes], ColorBlend [stability-ComfyUI-nodes], RandomInt [comfyui-xin-nodes], SDXLPromptStyler [ComfyUI-Eagle-PNGInfo], SDXLPromptStyler [sdxl_prompt_styler]

how to fix it?Thx
My computer is apple M1 macbook pro

**Comment by shenwang2** [comment]
using the newest comfyui？

**Comment by shenwang2** [comment]
i have the same problem，because using the newest comfyui

**Comment by littleyeson** [comment]
copy the new requirements.txt in comfyui-art-venture. Using terminal the In comfyui-art-venture dir. pip install -r requirements.txt  update can fix it.

**Comment by shenwang2** [comment]
where is the new requirements.txt

**Comment by lvdougao1** [comment]
where is the new requirements.txt

**Comment by eflin1** [comment]
same problem

**Comment by wordbrew** [comment]
still happening, it seems

**Comment by jordanl61** [comment]
Reinstalled requirements.txt. Still not working.

**Comment by brbbbq** [comment]
I'm having this issue as well trying to do a clean reinstall of ComfyUI, I'm getting this error in the terminal:
```
Traceback (most recent call last):
  File "J:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\__init__.py", line 13, in <module>
    from .modules.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\nodes.py", line 54, in <module>
    from .inpaint import (
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\nodes.py", line 8, in <module>
    from .lama import LaMaInpaint
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture\modules\inpaint\lama\__init__.py", line 6, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'

Cannot import J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture module for custom nodes: No module named 'omegaconf'
```

**Comment by brbbbq** [comment]
I found this tip in a previous post:
https://github.com/sipherxyz/comfyui-art-venture/issues/13#issuecomment-1892156262

I navigated to "comfyui_windows portable/python_embeded/lib/site_packages" and did a "pip install omegaconf" in the cmd window, and that solved my issue.

**Comment by Cheesas** [comment]
> I found this tip in a previous post: [#13 (comment)](https://github.com/sipherxyz/comfyui-art-venture/issues/13#issuecomment-1892156262)
> 
> I navigated to "comfyui_windows portable/python_embeded/lib/site_packages", did a "pip install omegaconf" in the cmd window, and that solved my issue.

As a new user here, I did all this steps and did not fixed until I close the web browser, and restart python as well. I don't know if this "restart server" does the same as fully restart everything but it did the trick for me.

Much appreciated for your tip!
