### ISSUE TITLE
Cannot import No module named 'omegaconf'

### ISSUE THREAD

**Issue by mayichen1987** [sipherxyz/comfyui-art-venture#3]
Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture module for custom nodes: No module named 'omegaconf'

(IMPORT FAILED): F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture

**Comment by esqanor** [comment]
Same here after installing a normal version of ComfyUI. With portable version I get (IMPORT FAILED) ModuleNotFoundError: No module named 'segment_anything'

**Comment by QaisMalkawi** [comment]
same here!

**Comment by XTorX** [comment]
Is there a solution for this?

**Comment by XTorX** [comment]
Ok got it. Go in the update folder:
....\Desktop\ComfyUI\ComfyUI_windows_portable\update>
cmd
..\python_embeded\python.exe -s -m pip install omegaconf
