### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### ISSUE THREAD

**Issue by myprivacygithub** [sipherxyz/comfyui-art-venture#51]
![image](https://github.com/user-attachments/assets/7da73e71-713c-4cf5-889f-36588f5b5252)

**Comment by tungnguyensipher** [comment]
This is likely due to python 3.12 deprecated some modules. You need to update to new pip for python 3.12.

Have a look at: https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

**Comment by myprivacygithub** [comment]
Thanks, its working now.
