### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by thefirstLeonliao** [sipherxyz/comfyui-art-venture#55]
cannot checkout to invalid path 'modules/controlnet/aux.py

**Comment by tungnguyensipher** [comment]
Can you provide the log in console. I couldn't reproduce it on my end.

**Comment by tungnguyensipher** [comment]
Should be fixed now

**Comment by bananasss00** [comment]
> Should be fixed now

work now

**Comment by thefirstLeonliao** [comment]
work now，thank you
